name: Build and push the latest build to staging
on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push staging images
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: poi1
          folder: src/
          dockerfile: Dockerfile